import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,SKILLS} from '../dist/engine.mjs';
function advance(g,seconds){for(let i=0;i<seconds*60;i++)g.step(1/60);}
test('a placed toy is physically completed and pays exactly once',()=>{const g=new Game(10);g.place('ball',450,300);const t=g.s.rooms[0].toys[0];assert.equal(g.s.gold,6);advance(g,15);assert.equal(g.s.stats.ball,1);assert.equal(g.s.gold,9);assert.equal(g.complete(g.s.cats[0],t),false);assert.equal(g.s.gold,9);});
test('skill gates cannot be bypassed with money',()=>{const g=new Game();g.s.gold=1000;assert.equal(g.buySkill('floor3'),false);assert.equal(g.buySkill('mice'),false);assert.equal(g.buySkill('room'),false);assert.equal(g.s.gold,1000);});
test('ball becomes exactly two mice, all rewards paid once',()=>{const g=new Game(7);g.s.skills.mice=true;g.place('ball',450,300);g.s.rooms[0].toys[0].z=0;g.complete(g.s.cats[0],g.s.rooms[0].toys[0]);assert.deepEqual(g.s.rooms[0].toys.map(t=>t.kind),['mouse','mouse']);advance(g,30);assert.equal(g.s.stats.mouse,2);assert.equal(g.s.gold,11);});
test('house becomes tunnel with one completion payout after ten passes',()=>{const g=new Game(22);g.s.skills.house=true;g.s.gold=200;g.place('house',450,300);advance(g,65);assert.equal(g.s.stats.house,1);assert.equal(g.s.stats.tunnel,10);assert.equal(g.s.gold,249);assert.equal(g.s.rooms[0].toys.length,0);});
test('rod and scratch transformations are reachable by natural cat interactions',()=>{const g=new Game(31);g.s.skills.rod=true;g.s.skills.scratch=true;g.s.gold=2000;g.place('rod',300,300);g.place('scratch',520,320);advance(g,80);assert.equal(g.s.stats.rod,1);assert.equal(g.s.stats.feather,1);assert.equal(g.s.stats.scratch,25);assert.equal(g.s.stats.surf,3);assert.equal(g.s.gold,2489);});
test('both rooms progress without viewing the second room',()=>{const g=new Game(39);g.s.rooms.push({name:'Salon',toys:[],autoTimer:0});g.addCat(1);g.place('ball',450,300,1);advance(g,20);assert.equal(g.s.active,0);assert.equal(g.s.stats.ball,1);});
test('save/load preserves in-flight actions and deterministic RNG',()=>{const g=new Game(43);g.s.skills.mice=true;g.place('ball',600,420);advance(g,.5);const re=Game.load(g.save());assert.ok(re);advance(g,30);advance(re,30);assert.deepEqual(re.s,g.s);});
test('bankrupt state recovers without reset and free ball is cooldown protected',()=>{const g=new Game();g.s.gold=0;assert.ok(g.starterBall());assert.equal(g.starterBall(),false);advance(g,20);assert.ok(g.s.gold>=3);assert.equal(g.starterBall(),false);advance(g,11);assert.ok(g.starterBall());});
test('invalid and corrupted saves are rejected',()=>{assert.equal(Game.load('{'),null);const g=new Game();g.s.gold=-1;assert.equal(Game.load(g.save()),null);g.s.gold=5;g.s.cats[0].x=null;assert.equal(Game.load(g.save()),null);});
test('room capacity and insufficient cash never charge for a failed placement',()=>{const g=new Game();g.s.gold=100;for(let i=0;i<g.purchaseLimit();i++)assert.ok(g.place('ball',450,300));const money=g.s.gold;assert.equal(g.place('ball',450,300),false);assert.equal(g.s.gold,money);g.s.rooms[0].toys=[];g.s.gold=0;assert.equal(g.place('ball',450,300),false);assert.equal(g.s.gold,0);});
test('automation respects gold reserve and stops charging while full',()=>{const g=new Game();g.s.skills.auto=true;g.s.auto=true;g.s.gold=2;advance(g,10);assert.equal(g.s.gold,2);g.s.gold=100;for(let i=0;i<12;i++)g.spawn('house',450,300,0);g.s.cats=[];advance(g,10);assert.equal(g.s.gold,100);});
