import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../dist/engine.mjs';
import {BALLS,stepBall,DOOR,FURNITURE,collideFurniture} from '../dist/physics.mjs';
import {Camera} from '../dist/camera.mjs';
const advance=(g,n)=>{for(let i=0;i<n*60;i++)g.step(1/60);};
const unlockRoom=g=>{g.s.skills.house=true;g.s.skills.room=true;g.s.rooms.push({name:'Oyun odası',toys:[],autoTimer:0});};
test('three ball types have ordered heights and monetary rewards',()=>{
 const heights={};for(const kind of Object.keys(BALLS)){const g=new Game(9);g.s.gold=20;g.s.skills.mice=true;g.s.skills.balls=true;g.s.skills.basket=true;g.place(kind,450,350);const t=g.s.rooms[0].toys[0];let max=0;for(let i=0;i<100;i++){stepBall(t,1/60,0,1);max=Math.max(max,t.z);}heights[kind]=max;assert.equal(g.complete(g.s.cats[0],{...t}),false);advance(g,35);assert.equal(g.s.stats.ball,1);assert.equal(g.s.stats.mouse,2);assert.equal(g.s.gold,20+({ball:3,football:6,basketball:9}[kind]));}
 assert.ok(heights.basketball>heights.ball&&heights.ball>heights.football);
});
test('airborne toys cannot pay and a kick changes motion without charging or paying',()=>{const g=new Game();g.place('ball',450,300);const t=g.s.rooms[0].toys[0],cat=g.s.cats[0];t.age=1;t.z=80;assert.equal(g.complete(cat,t),false);const gold=g.s.gold;assert.ok(g.kickBall(t.id,400,0));assert.ok(t.vx>0&&t.vz>0);assert.equal(g.s.gold,gold);assert.equal(g.s.stats.ball,0);assert.equal(g.kickBall(t.id),false);});
test('a ball crosses an open doorway, its chasing cat follows and completes it',()=>{const g=new Game(13);unlockRoom(g);const c=g.s.cats[0];c.x=800;c.y=DOOR.y;c.mode='chase';const t=g.spawn('ball',840,DOOR.y,0,{vx:400,vy:0,z:0,vz:0});c.target=t.id;advance(g,.2);assert.ok(g.s.rooms[1].toys.includes(t));advance(g,20);assert.equal(g.s.stats.ball,1);assert.ok(g.s.stats.doorPass>=2);assert.equal(c.room,1);});
test('closed, missed and full-room doorways contain balls without exceeding capacity',()=>{for(const [roomCount,allow,y]of [[1,true,DOOR.y],[2,true,450],[2,false,DOOR.y]]){const t={kind:'ball',x:845,y,z:0,vz:0,vx:400,vy:0};let room=0;for(let i=0;i<60;i++)room=stepBall(t,1/60,room,roomCount,allow).room;assert.equal(room,0);assert.ok(t.x<=855);}});
test('furniture collision reflects floor-level balls and permits high flight',()=>{const rect=FURNITURE[0],t={x:rect.x+50,y:rect.y+rect.h+5,z:0,vx:0,vy:-100};assert.ok(collideFurniture(t,rect));assert.ok(t.vy>0);t.y=rect.y+rect.h+5;t.z=100;assert.equal(collideFurniture(t,rect),false);});
test('bed persists, cat sleeps voluntarily, reward occurs once on waking; save remains deterministic',()=>{const g=new Game(17);g.s.gold=60;g.place('bed',450,350);const bed=g.s.rooms[0].toys[0];for(let i=0;i<20*60&&g.s.cats[0].mode!=='sleep';i++)g.step(1/60);const c=g.s.cats[0];assert.equal(c.mode,'sleep');assert.equal(g.s.gold,20);const re=Game.load(g.save());assert.ok(re);advance(g,7);advance(re,7);assert.deepEqual(g.s,re.s);assert.equal(g.s.stats.naps,1);assert.equal(g.s.gold,22);assert.equal(g.s.rooms[0].toys[0].id,bed.id);advance(g,8);assert.equal(g.s.stats.naps,1);});
test('occupied beds are exclusive and sleeping cats are not pushed by other cats',()=>{const g=new Game(18);g.s.gold=50;g.place('bed',450,350);const bed=g.s.rooms[0].toys[0],c=g.s.cats[0];c.target=bed.id;c.x=bed.x;c.y=bed.y;g.complete(c,bed);const other=g.addCat(0);other.x=c.x+1;other.y=c.y;advance(g,2);assert.equal(c.x,bed.x);assert.equal(c.y,bed.y);assert.equal(g.s.cats.filter(c=>c.mode==='sleep').length,1);});
test('a third bed fails without charging, preserving toy space',()=>{const g=new Game();g.s.gold=100;assert.ok(g.place('bed',200,300));assert.ok(g.place('bed',500,300));assert.equal(g.place('bed',700,300),false);assert.equal(g.s.gold,20);});
test('v1 migration retains progress and preserves an existing grounded toy',()=>{const g=new Game(6);g.place('ball',450,300);const old=JSON.parse(g.save());old.version=1;for(const k of ['football','basketball','naps','bounces','doorPass'])delete old.stats[k];for(const c of old.cats){delete c.plays;delete c.lastNap;}for(const t of old.rooms[0].toys){delete t.z;delete t.vz;}const loaded=Game.load(JSON.stringify(old));assert.ok(loaded);assert.equal(loaded.s.gold,old.gold);assert.equal(loaded.s.rng,old.rng);assert.equal(loaded.s.rooms[0].toys[0].z,0);advance(loaded,20);assert.equal(loaded.s.stats.ball,1);});
test('camera maps clicks after pan/zoom, anchors the cursor, and fits both rooms',()=>{const c=new Camera(),w=1200,h=800;const before=c.world(630,420,w,h);c.zoomAt(1.4,630,420,w,h,2);const after=c.world(630,420,w,h);assert.ok(Math.abs(before.x-after.x)<1e-9&&Math.abs(before.y-after.y)<1e-9);c.pan(-100,20,w,h,2);const v=c.view(w,h),p=c.world(200,300,w,h);assert.ok(Math.abs(p.x*v.scale+v.ox-200)<1e-9);c.fit(2,w,h);const fitted=c.view(w,h);assert.ok(fitted.ox>=0&&1800*fitted.scale+fitted.ox<=w);});
